
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'BlocksActionBlock': typeof import("../components/blocks/ActionBlock.vue")['default']
    'BlocksBlockDeliveryCalc': typeof import("../components/blocks/BlockDeliveryCalc.vue")['default']
    'BlocksBlockPayment': typeof import("../components/blocks/BlockPayment.vue")['default']
    'BlocksBlockUserInfo': typeof import("../components/blocks/BlockUserInfo.vue")['default']
    'BlocksHeroSlider': typeof import("../components/blocks/HeroSlider.vue")['default']
    'BlocksHits': typeof import("../components/blocks/Hits.vue")['default']
    'BlocksRecomendedBlock': typeof import("../components/blocks/RecomendedBlock.vue")['default']
    'CardProductsCard': typeof import("../components/card/ProductsCard.vue")['default']
    'HeadPageHead': typeof import("../components/head/PageHead.vue")['default']
    'HeadShopHead': typeof import("../components/head/ShopHead.vue")['default']
    'ModalAuth': typeof import("../components/modal/ModalAuth.vue")['default']
    'ModalAuthNew': typeof import("../components/modal/auth/AuthNew.vue")['default']
    'ModalAuthVerification': typeof import("../components/modal/auth/AuthVerification.vue")['default']
    'ModalAuthEmailForm': typeof import("../components/modal/auth/EmailForm.vue")['default']
    'SharedFooter': typeof import("../components/shared/Footer.vue")['default']
    'SharedHeader': typeof import("../components/shared/Header.vue")['default']
    'SingleAbout': typeof import("../components/single/SingleAbout.vue")['default']
    'SingleCharacter': typeof import("../components/single/SingleCharacter.vue")['default']
    'SingleIdeas': typeof import("../components/single/SingleIdeas.vue")['default']
    'UiAddToCart': typeof import("../components/ui/AddToCart.vue")['default']
    'UiBreadcrumbs': typeof import("../components/ui/Breadcrumbs.vue")['default']
    'UiColorSelect': typeof import("../components/ui/ColorSelect.vue")['default']
    'UiDefaultBtn': typeof import("../components/ui/DefaultBtn.vue")['default']
    'UiIconBtn': typeof import("../components/ui/IconBtn.vue")['default']
    'UiInputPhone': typeof import("../components/ui/InputPhone.vue")['default']
    'UiInputs': typeof import("../components/ui/Inputs.vue")['default']
    'UiLogo': typeof import("../components/ui/Logo.vue")['default']
    'UiNav': typeof import("../components/ui/Nav.vue")['default']
    'UiQty': typeof import("../components/ui/Qty.vue")['default']
    'UiSocials': typeof import("../components/ui/Socials.vue")['default']
    'UiYaYaButton': typeof import("../components/ui/YaYaButton.vue")['default']
    'UiYaYaSplit': typeof import("../components/ui/YaYaSplit.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBlocksActionBlock': typeof import("../components/blocks/ActionBlock.vue")['default']
    'LazyBlocksBlockDeliveryCalc': typeof import("../components/blocks/BlockDeliveryCalc.vue")['default']
    'LazyBlocksBlockPayment': typeof import("../components/blocks/BlockPayment.vue")['default']
    'LazyBlocksBlockUserInfo': typeof import("../components/blocks/BlockUserInfo.vue")['default']
    'LazyBlocksHeroSlider': typeof import("../components/blocks/HeroSlider.vue")['default']
    'LazyBlocksHits': typeof import("../components/blocks/Hits.vue")['default']
    'LazyBlocksRecomendedBlock': typeof import("../components/blocks/RecomendedBlock.vue")['default']
    'LazyCardProductsCard': typeof import("../components/card/ProductsCard.vue")['default']
    'LazyHeadPageHead': typeof import("../components/head/PageHead.vue")['default']
    'LazyHeadShopHead': typeof import("../components/head/ShopHead.vue")['default']
    'LazyModalAuth': typeof import("../components/modal/ModalAuth.vue")['default']
    'LazyModalAuthNew': typeof import("../components/modal/auth/AuthNew.vue")['default']
    'LazyModalAuthVerification': typeof import("../components/modal/auth/AuthVerification.vue")['default']
    'LazyModalAuthEmailForm': typeof import("../components/modal/auth/EmailForm.vue")['default']
    'LazySharedFooter': typeof import("../components/shared/Footer.vue")['default']
    'LazySharedHeader': typeof import("../components/shared/Header.vue")['default']
    'LazySingleAbout': typeof import("../components/single/SingleAbout.vue")['default']
    'LazySingleCharacter': typeof import("../components/single/SingleCharacter.vue")['default']
    'LazySingleIdeas': typeof import("../components/single/SingleIdeas.vue")['default']
    'LazyUiAddToCart': typeof import("../components/ui/AddToCart.vue")['default']
    'LazyUiBreadcrumbs': typeof import("../components/ui/Breadcrumbs.vue")['default']
    'LazyUiColorSelect': typeof import("../components/ui/ColorSelect.vue")['default']
    'LazyUiDefaultBtn': typeof import("../components/ui/DefaultBtn.vue")['default']
    'LazyUiIconBtn': typeof import("../components/ui/IconBtn.vue")['default']
    'LazyUiInputPhone': typeof import("../components/ui/InputPhone.vue")['default']
    'LazyUiInputs': typeof import("../components/ui/Inputs.vue")['default']
    'LazyUiLogo': typeof import("../components/ui/Logo.vue")['default']
    'LazyUiNav': typeof import("../components/ui/Nav.vue")['default']
    'LazyUiQty': typeof import("../components/ui/Qty.vue")['default']
    'LazyUiSocials': typeof import("../components/ui/Socials.vue")['default']
    'LazyUiYaYaButton': typeof import("../components/ui/YaYaButton.vue")['default']
    'LazyUiYaYaSplit': typeof import("../components/ui/YaYaSplit.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BlocksActionBlock: typeof import("../components/blocks/ActionBlock.vue")['default']
export const BlocksBlockDeliveryCalc: typeof import("../components/blocks/BlockDeliveryCalc.vue")['default']
export const BlocksBlockPayment: typeof import("../components/blocks/BlockPayment.vue")['default']
export const BlocksBlockUserInfo: typeof import("../components/blocks/BlockUserInfo.vue")['default']
export const BlocksHeroSlider: typeof import("../components/blocks/HeroSlider.vue")['default']
export const BlocksHits: typeof import("../components/blocks/Hits.vue")['default']
export const BlocksRecomendedBlock: typeof import("../components/blocks/RecomendedBlock.vue")['default']
export const CardProductsCard: typeof import("../components/card/ProductsCard.vue")['default']
export const HeadPageHead: typeof import("../components/head/PageHead.vue")['default']
export const HeadShopHead: typeof import("../components/head/ShopHead.vue")['default']
export const ModalAuth: typeof import("../components/modal/ModalAuth.vue")['default']
export const ModalAuthNew: typeof import("../components/modal/auth/AuthNew.vue")['default']
export const ModalAuthVerification: typeof import("../components/modal/auth/AuthVerification.vue")['default']
export const ModalAuthEmailForm: typeof import("../components/modal/auth/EmailForm.vue")['default']
export const SharedFooter: typeof import("../components/shared/Footer.vue")['default']
export const SharedHeader: typeof import("../components/shared/Header.vue")['default']
export const SingleAbout: typeof import("../components/single/SingleAbout.vue")['default']
export const SingleCharacter: typeof import("../components/single/SingleCharacter.vue")['default']
export const SingleIdeas: typeof import("../components/single/SingleIdeas.vue")['default']
export const UiAddToCart: typeof import("../components/ui/AddToCart.vue")['default']
export const UiBreadcrumbs: typeof import("../components/ui/Breadcrumbs.vue")['default']
export const UiColorSelect: typeof import("../components/ui/ColorSelect.vue")['default']
export const UiDefaultBtn: typeof import("../components/ui/DefaultBtn.vue")['default']
export const UiIconBtn: typeof import("../components/ui/IconBtn.vue")['default']
export const UiInputPhone: typeof import("../components/ui/InputPhone.vue")['default']
export const UiInputs: typeof import("../components/ui/Inputs.vue")['default']
export const UiLogo: typeof import("../components/ui/Logo.vue")['default']
export const UiNav: typeof import("../components/ui/Nav.vue")['default']
export const UiQty: typeof import("../components/ui/Qty.vue")['default']
export const UiSocials: typeof import("../components/ui/Socials.vue")['default']
export const UiYaYaButton: typeof import("../components/ui/YaYaButton.vue")['default']
export const UiYaYaSplit: typeof import("../components/ui/YaYaSplit.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBlocksActionBlock: typeof import("../components/blocks/ActionBlock.vue")['default']
export const LazyBlocksBlockDeliveryCalc: typeof import("../components/blocks/BlockDeliveryCalc.vue")['default']
export const LazyBlocksBlockPayment: typeof import("../components/blocks/BlockPayment.vue")['default']
export const LazyBlocksBlockUserInfo: typeof import("../components/blocks/BlockUserInfo.vue")['default']
export const LazyBlocksHeroSlider: typeof import("../components/blocks/HeroSlider.vue")['default']
export const LazyBlocksHits: typeof import("../components/blocks/Hits.vue")['default']
export const LazyBlocksRecomendedBlock: typeof import("../components/blocks/RecomendedBlock.vue")['default']
export const LazyCardProductsCard: typeof import("../components/card/ProductsCard.vue")['default']
export const LazyHeadPageHead: typeof import("../components/head/PageHead.vue")['default']
export const LazyHeadShopHead: typeof import("../components/head/ShopHead.vue")['default']
export const LazyModalAuth: typeof import("../components/modal/ModalAuth.vue")['default']
export const LazyModalAuthNew: typeof import("../components/modal/auth/AuthNew.vue")['default']
export const LazyModalAuthVerification: typeof import("../components/modal/auth/AuthVerification.vue")['default']
export const LazyModalAuthEmailForm: typeof import("../components/modal/auth/EmailForm.vue")['default']
export const LazySharedFooter: typeof import("../components/shared/Footer.vue")['default']
export const LazySharedHeader: typeof import("../components/shared/Header.vue")['default']
export const LazySingleAbout: typeof import("../components/single/SingleAbout.vue")['default']
export const LazySingleCharacter: typeof import("../components/single/SingleCharacter.vue")['default']
export const LazySingleIdeas: typeof import("../components/single/SingleIdeas.vue")['default']
export const LazyUiAddToCart: typeof import("../components/ui/AddToCart.vue")['default']
export const LazyUiBreadcrumbs: typeof import("../components/ui/Breadcrumbs.vue")['default']
export const LazyUiColorSelect: typeof import("../components/ui/ColorSelect.vue")['default']
export const LazyUiDefaultBtn: typeof import("../components/ui/DefaultBtn.vue")['default']
export const LazyUiIconBtn: typeof import("../components/ui/IconBtn.vue")['default']
export const LazyUiInputPhone: typeof import("../components/ui/InputPhone.vue")['default']
export const LazyUiInputs: typeof import("../components/ui/Inputs.vue")['default']
export const LazyUiLogo: typeof import("../components/ui/Logo.vue")['default']
export const LazyUiNav: typeof import("../components/ui/Nav.vue")['default']
export const LazyUiQty: typeof import("../components/ui/Qty.vue")['default']
export const LazyUiSocials: typeof import("../components/ui/Socials.vue")['default']
export const LazyUiYaYaButton: typeof import("../components/ui/YaYaButton.vue")['default']
export const LazyUiYaYaSplit: typeof import("../components/ui/YaYaSplit.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
